PCyP.WebSite/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PCyP.Domain.DAL;
using PCyP.Domain.Biz;
using System.Web.Mvc;
using PCyP.Domain.BLL;

namespace PCyP.WebSite.Controllers
{
    public class CategoryController : Controller
    {

        // GET: Category
        public ActionResult Index()
        {
            return View(CategoryBusiness.Instance.GetCategoryList());
        }

        // GET: Category/Details/5
        public ActionResult Details(string id)
        {
            return View(CategoryBusiness.Instance.GetCategoryDetails(id));
        }

        // GET: Category/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        [HttpPost]
        public ActionResult Create(Category model)
        {
            try
            {

                CategoryBusiness.Instance.Add(model);
                return Redirect("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Category/Edit/5
        public ActionResult Edit(string id)
        {
            return View(CategoryBusiness.Instance.GetCategoryDetails(id));
        }

        // POST: Category/Edit/5
        [HttpPost]
        public ActionResult Edit(Category model)
        {
            try
            {
                CategoryBusiness.Instance.EditCategory(model);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Category/Delete/5
        public ActionResult Delete(string id)
        {
            return View(CategoryBusiness.Instance.GetCategoryDetails(id));
        }

        // POST: Category/Delete/5
        [HttpPost]
        public ActionResult Delete(Category model)
        {
            try
            {
                // TODO: Add delete logic here
                CategoryBusiness.Instance.DeleteCategory(model);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PCyP.WebSite/Controllers/InstructorController.cs
using PCyP.Domain.Biz;
using PCyP.Domain.BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PCyP.WebSite.Controllers
{
    public class InstructorController : Controller
    {
        // GET: Instructor
        public ActionResult Index()
        {
            return View(InstructorBusiness.Instance.GetInstructorList());
        }

        // GET: Instructor/Details/5
        public ActionResult Details(string id)
        {
            return View(InstructorBusiness.Instance.GetInstructorDetails(id));
        }

        // GET: Instructor/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Instructor/Create
        [HttpPost]
        public ActionResult Create(Instructor instructor)
        {
            try
            {
                // TODO: Add insert logic here
                InstructorBusiness.Instance.Add(instructor);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Instructor/Edit/5
        public ActionResult Edit(string id)
        {
            return View(InstructorBusiness.Instance.GetInstructorDetails(id));
        }

        // POST: Instructor/Edit/5
        [HttpPost]
        public ActionResult Edit(Instructor instructor)
        {
            try
            {
                // TODO: Add update logic here
                InstructorBusiness.Instance.EditInstructor(instructor);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Instructor/Delete/5
        public ActionResult Delete(string id)
        {
            return View(InstructorBusiness.Instance.GetInstructorDetails(id));
        }

        // POST: Instructor/Delete/5
        [HttpPost]
        public ActionResult Delete(Instructor instructor)
        {
            try
            {
                // TODO: Add delete logic here
                InstructorBusiness.Instance.DeleteInstructor(instructor);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PCyP.WebSite/Controllers/StudentController.cs
using PCyP.Domain.Biz;
using PCyP.Domain.BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PCyP.WebSite.Controllers
{
    public class StudentController : Controller
    {
        // GET: Student
        public ActionResult Index()
        {
            return View(StudentBusiness.Instance.GetStudentList());
        }

        // GET: Student/Details/5
        public ActionResult Details(string id)
        {
            return View(StudentBusiness.Instance.GetStudentDetails(id));
        }

        // GET: Student/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Student/Create
        [HttpPost]
        public ActionResult Create(Student student)
        {
            try
            {
                // TODO: Add insert logic here
                StudentBusiness.Instance.Add(student);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Student/Edit/5
        public ActionResult Edit(string id)
        {
            return View(StudentBusiness.Instance.GetStudentDetails(id));
        }

        // POST: Student/Edit/5
        [HttpPost]
        public ActionResult Edit(Student student)
        {
            try
            {
                // TODO: Add update logic here
                StudentBusiness.Instance.EditStudent(student);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Student/Delete/5
        public ActionResult Delete(string id)
        {
            return View(StudentBusiness.Instance.GetStudentDetails(id));
        }

        // POST: Student/Delete/5
        [HttpPost]
        public ActionResult Delete(Student student)
        {
            try
            {
                // TODO: Add delete logic here
                StudentBusiness.Instance.DeleteStudent(student);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PCyP.WebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Programacion Concurrente y Paralela", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Categorias", "Index", "Category")</li>
                    <li>@Html.ActionLink("Estudiantes", "Index", "Student")</li>
                    <li>@Html.ActionLink("Instructores", "Index", "Instructor")</li>
                    <li>@Html.ActionLink("Gestor", "Index", "Gestor")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>